[blurry]
domain = 'blurry-themes.netlify.app'
markdown_file_jinja_template_extension = '.html.jinja'
maximum_image_width = 750
thumbnail_width = 285
templates_directory_name = 'themes/pico'

[blurry.schema_data.author]
'@type' = 'Person'
name = 'John Franey'
url = 'https://johnfraney.ca'

[blurry.schema_data.sourceOrganization]
name = 'Blurry'
